### ISSUE TITLE
Is this code for review?

### ISSUE THREAD

**Issue by Greedquest** [cristianbuse/VBA-WeakReference#2]
Hey, you should post this code on codereview, there are a few comments I'd like to make; I've been working on similar code for dereferencing pointers into a com variant. Also I think it's a great way of getting exposure for the code and making it useful to more people!

**Comment by cristianbuse** [comment]
Hey, I might have time to do this tomorrow. Meanwhile, couldn't you write your comments here?

**Comment by Greedquest** [comment]
Well I was gonna mention a few things like use of the CopyMemory API on Windows, magic number 2, naming things differently so that you can reduce the size of the explanation text required etc. If it's all the same to you then I'd prefer to write it up on CR so other people could maybe benefit, and also so my own comments could be subject to feedback from other users.

If not then I guess I could go into more detail here, but some of the points I've seen crop up a number of times on CR (both things you've done well which others haven't and things where I'd suggest changes), so having a public post would be beneficial to everyone! I think this is a pretty insightful implementation, I've seen Matt's version and this and yours definitely has some merits, so putting it up for review could generate some interesting insights for you

**Comment by cristianbuse** [comment]
I've been quite busy these days. If you have time to write it up on CR then I would be glad. The repository has an MIT license so  you can pretty much do whatever you want with the code as long as you maintain the copyright or provide a link to the repository so that people know they can use the code accordingly. It's very permissive.
If you do write it then please come back here and give me the link. I would be interested in what you and others have to say.
If not, I will do my best to write it myself sometime this week.

Cheers!

**Comment by cristianbuse** [comment]
Hi,

Here's the [CR link](https://codereview.stackexchange.com/questions/245660/simulated-weakreference-class)
Looking forward for your comments!

Cheers!

**Comment by Greedquest** [comment]
Just to let you know in case you hadn't seen it, I've made a few comments on the post

**Comment by cristianbuse** [comment]
I've quickly read it already. Outstanding review. I hope I will have some time this weekend to dive into all the details and fully understand all you wrote. Thanks! 
 
  On Wed, 29 Jul 2020 at 18:50, Greedquest<notifications@github.com> wrote:   


Just to let you know in case you hadn't seen it, I've made a few comments on the post

**Comment by cristianbuse** [comment]
I have finally provided an answer in reply to your answer on CR. Sorry for taking so long! I will update this repository as soon as I have time for it.

**Comment by Greedquest** [comment]
I saw, glad you found it useful!

**Comment by cristianbuse** [comment]
Yes. Thank you! I blindly thought the memory will not be reused if there was a "remote" variant pointing to it. It is quite unfortunate that I could not make it work for non-VB objects (e.g. Range, Collection etc.) but at least it now works for VB classes. I've tested a lot of different ideas over the last month (hence the slow reply) but they all lead me nowhere or the risk was too great (redirecting IUNknown::Release). I've never used CR before but I can see the benefits now. Thanks for that as well. I never had anybody review any of my code before.

Best of luck,
Cristian

**Comment by cristianbuse** [comment]
I've just noticed in your stack [profile](https://stackoverflow.com/users/6609896/greedo?tab=profile) that you live in London. Is that correct? I also live in London. I live in Bermondsey and I work for CBRE. I was just wondering if it happens that we live in the same area or maybe work for the same company. We certainly both enjoy VBA and solving problems. I apologize inadvance if this is offending you in any way. Just let me know and I will never ask personal questions again. Thanks!
